// const data = [
// 	{
// 		title: "Ant-Man and the Wasp: Quantumania",
// 		media_type: "movies",
// 		genre: ["Adventure", "SciFi", "Comedy"],
// 		date: 2023,
// 		rating: 75,
// 	},
// 	{
// 		title: "Black Panther: Wakanda Forever",
// 		media_type: "movies",
// 		genre: ["Action", "Adventure", "SciFi"],
// 		date: 2022,
// 		rating: 64,
// 	},
// 	{
// 		title: "Your Place or Mine",
// 		media_type: "movies",
// 		genre: ["Romance", "Comedy"],
// 		date: 2023,
// 		rating: 69,
// 	},
// 	{
// 		title: "Infinity Pool",
// 		media_type: "movies",
// 		genre: ["Horror", "SciFi", "Thriller"],
// 		date: 2023,
// 		rating: 60,
// 	},
// 	{
// 		title: "Squared Love All Over Again",
// 		media_type: "movies",
// 		genre: ["Romance", "Comedy"],
// 		date: 2023,
// 		rating: 85,
// 	},
// 	{
// 		title: "Puss in Boots: The Last Wish",
// 		media_type: "movies",
// 		genre: ["Animation", "Adventure", "Comedy", "Family", "Fantasy"],
// 		date: 2022,
// 		rating: 70,
// 	},
// 	{
// 		title: "Re/Member",
// 		media_type: "movies",
// 		genre: ["Horror", "Thriller", "Fantasy"],
// 		date: 2022,
// 		rating: 62,
// 	},
// 	{
// 		title: "Somebody I Used to Know",
// 		media_type: "movies",
// 		genre: ["Romance", "Comedy", "Drama"],
// 		date: 2023,
// 		rating: 76,
// 	},

// 	{
// 		title: "The Flash",
// 		media_type: "movies",
// 		genre: ["SciFi", "Action", "Adventure"],
// 		date: 2023,
// 		rating: 77,
// 	},
// 	{
// 		title: "Avatar: The Way of Water",
// 		media_type: "movies",
// 		genre: ["SciFi", "Adventure", "Action"],
// 		date: 2022,
// 		rating: 79,
// 	},
// 	{
// 		title: "Titanic",
// 		media_type: "movies",
// 		genre: ["Drama", "Romance"],
// 		date: 1997,
// 		rating: 69,
// 	},
// 	{
// 		title: "The Son",
// 		media_type: "movies",
// 		genre: ["Drama"],
// 		date: 2022,
// 		rating: 73,
// 	},
// 	{
// 		title: "Guardians of the Galaxy Volume 3",
// 		media_type: "movies",
// 		genre: ["SciFi", "Action", "Adventure"],
// 		date: 2023,
// 		rating: 68,
// 	},
// 	{
// 		title: "Plane",
// 		media_type: "movies",
// 		genre: ["Action", "Adventure", "Thriller"],
// 		date: 2023,
// 		rating: 61,
// 	},
// 	{
// 		title: "Empire of Light",
// 		media_type: "movies",
// 		genre: ["Drama", "Romance"],
// 		date: 2022,
// 		rating: 71,
// 	},
// 	{
// 		title: "Whitney Houston: I Wanna Dance with Somebody",
// 		media_type: "movies",
// 		genre: ["Music", "History", "Drama"],
// 		date: 2022,
// 		rating: 79,
// 	},
// 	{
// 		title: "The Fabelmans",
// 		media_type: "movies",
// 		genre: ["Drama"],
// 		date: 2022,
// 		rating: 60,
// 	},
// 	{
// 		title: "The Last of Us",
// 		media_type: "series",
// 		genre: ["Drama", "Action", "Adventure"],
// 		date: 2023,
// 		rating: 81.06,
// 	},
// 	{
// 		title: "You",
// 		media_type: "series",
// 		genre: ["Mystery", "Crime", "Drama"],
// 		date: 2018,
// 		rating: 68,
// 	},
// 	{
// 		title: "In Love All Over Again",
// 		media_type: "series",
// 		genre: ["Drama"],
// 		date: 2023,
// 		rating: 78.03,
// 	},
// 	{
// 		title: "The Flash",
// 		media_type: "series",
// 		genre: ["Drama", "Sci-Fi", "Fantasy"],
// 		date: 2014,
// 		rating: 81,
// 	},
// 	{
// 		title: "The Knockout",
// 		media_type: "series",
// 		genre: ["Crime", "Mystery", "Drama", "Action", "Adventure"],
// 		date: 2023,
// 		rating: 87,
// 	},
// 	{
// 		title: "Love to Hate You",
// 		media_type: "series",
// 		genre: ["Comedy", "Drama"],
// 		date: 2023,
// 		rating: 85,
// 	},
// 	{
// 		title: "Three-Body",
// 		media_type: "series",
// 		genre: ["Drama", "Sci-Fi", "Fantasy"],
// 		date: 2023,
// 		rating: 90,
// 	},
// 	{
// 		title: "The Gold",
// 		media_type: "series",
// 		genre: ["Crime", "Drama"],
// 		date: 2023,
// 		rating: 72,
// 	},
// 	{
// 		title: "Farzi",
// 		media_type: "series",
// 		genre: ["Drama", "Crime"],
// 		date: 2023,
// 		rating: 87.11,
// 	},
// 	{
// 		title: "One Piece",
// 		media_type: "series",
// 		genre: ["Action", "Adventure", "Comedy", "Animation"],
// 		date: 1999,
// 		rating: 85.61,
// 	},
// 	{
// 		title: "Tulsa King",
// 		media_type: "series",
// 		genre: ["Crime", "Drama"],
// 		date: 2022,
// 		rating: 85.19,
// 	},
// 	{
// 		title: "1923",
// 		media_type: "series",
// 		genre: ["Drama", "Western"],
// 		date: 2022,
// 		rating: 84.31,
// 	},
// 	{
// 		title: "Game of Thrones",
// 		media_type: "series",
// 		genre: ["Sci-Fi", "Fantasy", "Drama", "Action", "Adventure"],
// 		date: 2011,
// 		rating: 88.69,
// 	},
// 	{
// 		title: "Breaking Bad",
// 		media_type: "series",
// 		genre: ["Drama"],
// 		date: 2008,
// 		rating: 82,
// 	},
// 	{
// 		title: "The Nevers",
// 		media_type: "series",
// 		genre: ["Sci-Fi", "Fantasy", "Drama"],
// 		date: 2021,
// 		rating: 60,
// 	},
// 	{
// 		title: "Perfect Match",
// 		media_type: "series",
// 		genre: ["Reality"],
// 		date: 2023,
// 		rating: 86.41,
// 	},
// 	{
// 		title: "Attack on Titan",
// 		media_type: "series",
// 		genre: ["Sci-Fi", "Fantasy", "Animation", "Action", "Adventure"],
// 		date: 2013,
// 		rating: 85,
// 	},
// 	{
// 		title: "Under the Microscope",
// 		media_type: "series",
// 		genre: ["Drama", "Mystery"],
// 		date: 2023,
// 		rating: 84.36,
// 	},
// 	{
// 		title: "Harley Quinn",
// 		media_type: "series",
// 		genre: [
// 			"Sci-Fi",
// 			"Fantasy",
// 			"Animation",
// 			"Crime",
// 			"Action",
// 			"Adventure",
// 		],
// 		date: 2019,
// 		rating: 83.36,
// 	},
// ];
